### ISSUE TITLE
Run the app on custom context path

### ISSUE THREAD

**Issue by iahmad-khan** [gtca/mofaplus-shiny#10]
I am accessing the app behind a load balancer and I need to serve it on the context path /shiny/mfoa

if I re-write /shiny/mfoa with / as currently i have to do this becuase it is serving on /

then I lose the CSS and page is not rendering properly.

Is there a way to modify/change the app or dockerfile to serve it natively on /shiny/mfoa

**Comment by gtca** [comment]
We discovered that this is resolved by mounting the app to `/shiny/mofa/`, where the last slash seems to be important for Shiny. Seems to work!
